language: ruby
rvm:
  - 2.2
  - 2.1
  - 2.0.0
  - 1.9.3
env:
  - REDMINE_VERSION=3.3.0 VERBOSE=yes
  - REDMINE_VERSION=3.2.3 VERBOSE=yes
  - REDMINE_VERSION=3.1.6 VERBOSE=yes
install:
  - true
script:
  - export PLUGIN=redmine_xlsx_format_issue_exporter
  - export WORKSPACE=$(pwd)/workspace
  - export PATH_TO_PLUGIN=$(pwd)
  - export PATH_TO_REDMINE=$WORKSPACE/redmine
  - mkdir $WORKSPACE
  - bash -x ./.travis-init.sh -r || exit 1
  - bash -x ./.travis-init.sh -i || exit 1
  - bash -x ./.travis-init.sh -t || exit 1
  - bash -x ./.travis-init.sh -u || exit 1
